### ISSUE TITLE
Make proto-gen is broken.

### ISSUE THREAD

**Issue by SpicyLemon** [provenance-io/provenance#1083]
## Summary of Bug

Something that changed in #1034 caused `make proto-gen` to stop working.

## Version

`main` as of `c78df6fe`

## Steps to Reproduce

```
$ git checkout main
$ make proto-gen
Generating Protobuf files
if docker ps -a --format '{{.Names}}' | grep -Eq "^prov-proto-gen-v0.2$"; then \
		docker start -a prov-proto-gen-v0.2; \
	else \
		docker run --name prov-proto-gen-v0.2 -v /Users/danielwedul/git/provenance:/workspace --workdir /workspace tendermintdev/sdk-proto-gen:v0.2 \
			sh ./scripts/protocgen.sh; \
	fi
W0922 19:00:49.852699     127 services.go:38] No HttpRule found for method: Msg.AddAttribute
W0922 19:00:49.852724     127 services.go:38] No HttpRule found for method: Msg.UpdateAttribute
W0922 19:00:49.852729     127 services.go:38] No HttpRule found for method: Msg.DeleteAttribute
W0922 19:00:49.852732     127 services.go:38] No HttpRule found for method: Msg.DeleteDistinctAttribute
panic: interfacetype only supports messages with exactly one oneof declaration

goroutine 1 [running]:
github.com/regen-network/cosmos-proto/interfacetype.(*interfacetype).Generate(0x400000c078, 0x400031d540)
	/go/pkg/mod/github.com/regen-network/cosmos-proto@v0.3.1/interfacetype/interfacetype.go:56 +0x14bc
github.com/gogo/protobuf/protoc-gen-gogo/generator.(*Generator).runPlugins(0x400012b040, 0x400031d540)
	/go/pkg/mod/github.com/regen-network/protobuf@v1.3.3-alpha.regen.1/protoc-gen-gogo/generator/generator.go:1183 +0x7c
github.com/gogo/protobuf/protoc-gen-gogo/generator.(*Generator).generate(0x400012b040, 0x400031d540)
	/go/pkg/mod/github.com/regen-network/protobuf@v1.3.3-alpha.regen.1/protoc-gen-gogo/generator/generator.go:1232 +0x544
github.com/gogo/protobuf/protoc-gen-gogo/generator.(*Generator).GenerateAllFiles(0x400012b040)
	/go/pkg/mod/github.com/regen-network/protobuf@v1.3.3-alpha.regen.1/protoc-gen-gogo/generator/generator.go:1160 +0x208
github.com/gogo/protobuf/vanity/command.Generate(0x40000581e0, 0x12)
	/go/pkg/mod/github.com/regen-network/protobuf@v1.3.3-alpha.regen.1/vanity/command/command.go:131 +0x15c
main.main()
	/go/pkg/mod/github.com/regen-network/cosmos-proto@v0.3.1/protoc-gen-gocosmos/main.go:23 +0x1a0
--gocosmos_out: exit status 2
make: *** [proto-gen] Error 1
```

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by SpicyLemon** [comment]
In #1034, the `protocgen.sh` script didn't change, and the only `Makefile` change was an additional target.

So I'm guessing that there's something in the updated third-party protos that is problematic with our older method of generating code from protos.

We'll probably need to switch to the newer way of doing things with `buf` instead of `protoc`.

**Comment by SpicyLemon** [comment]
```
$ git log --oneline -10
86900d5b (HEAD -> main, origin/main, origin/HEAD) Update relayer scripts to integrate with services (#1068)
c78df6fe Update swagger, third-party protos, and related scripts. (#1034)
bc14bc7c Add the x/groups module. (#1045)
084e795b Replace uses of the deprecated Wrap and Wrapf sdkerrors functions. (#1042)
6be4ab2f Bump Cosmos-SDK to v0.46.1-pio-1-rc1 (from v0.45.5-pio-1). (#1016)
5bacec0a Bump github.com/spf13/viper from 1.12.0 to 1.13.0 (#1053)
d6212c96 Active participation and engagement module (#627) (#930)
1756a66c Update main after v1.12.0 (#1071)
46f9451e Bump bufbuild/buf-setup-action from 1.7.0 to 1.8.0 (#1070)
1ae7f35f Ignore tx gas limit if max gas limit is -1 (#1052)
```

If you
```
$ git checkout bc14bc7c
$ make proto-gen
```
It works. But with `c78df6fe` it fails.

**Comment by SpicyLemon** [comment]
Looks like we might be able to just remove the `interfacetype` from the gocosmos options.
