### ISSUE TITLE
Gov prop gives consensus failure when voting ends.

### ISSUE THREAD

**Issue by SpicyLemon** [provenance-io/provenance#1099]
## Summary of Bug

When the voting period ends on a governance proposal (e.g. an upgrade propsoal), the chain halts with: `ERR CONSENSUS FAILURE!!! err="GasMeter is not of type FeeGasMeter"`.

## Version

`dwedul/1006-fix-msg-fees` (in a state that shouldn't need any changes before being merged into `main`), commit `0baff2f3`.

## Steps to Reproduce

1. `git checkout dwedul/1006-fix-msg-fees`
2. If #1097 isn't merged yet: `git checkout dwedul/add-upgrade-test-script scripts/upgrade-test.sh`
3. `go mod tidy && go mod vendor`
4. `make clean build run-config`
5. `./scripts/upgrade-config.sh`
6. `make run`
7. In another terminal: `scripts/upgrade-test.sh brown`
8. Back in the first terminal, wait for voting to end on the newly submitted upgrade proposal.

Result (formatting changed to make it easier to read):
```
ERR CONSENSUS FAILURE!!!
err="GasMeter is not of type FeeGasMeter"
module=consensus
stack=
    goroutine 119 [running]:
    runtime/debug.Stack()
      runtime/debug/stack.go:24 +0x64
    github.com/tendermint/tendermint/consensus.(*State).receiveRoutine.func2()
      github.com/tendermint/tendermint@v0.34.21/consensus/state.go:727 +0x44
    panic({0x105251960, 0x1055ffb00})
      runtime/panic.go:884 +0x204
    github.com/provenance-io/provenance/internal/handlers.(*PioMsgServiceRouter).RegisterService.func2({{0x105626830, 0x140000540e8}, {0x105639f40, 0x14000d55680}, {{0xb, 0x0}, {0x140056bca67, 0x7}, 0xf0, {0x183e1da0, ...}, ...}, ...}, ...)
      github.com/provenance-io/provenance/internal/handlers/msg_service_router.go:129 +0xbd8
    github.com/cosmos/cosmos-sdk/x/gov.EndBlocker.func2({0x1, {0x1400131b948, 0x1, 0x1}, 0x2, 0x14000d54ac0, 0x140016af368, 0x140016af3b0, {0x140016af3c8, 0x1, ...}, ...})
      github.com/cosmos/cosmos-sdk@v0.46.0/x/gov/abci.go:73 +0xca0
    github.com/cosmos/cosmos-sdk/x/gov/keeper.Keeper.IterateActiveProposalsQueue({{0x10560d6b0, 0x140004f1b00}, {0x105627b38, 0x1400148cdc0}, {0x12f0df5d8, 0x1400051bce0}, {0x105617ab0, 0x140001b2f20}, {0x0, 0x0}, ...}, ...)
      github.com/cosmos/cosmos-sdk@v0.46.0/x/gov/keeper/keeper.go:163 +0x1cc
    github.com/cosmos/cosmos-sdk/x/gov.EndBlocker({{0x105626830, 0x140000540e8}, {0x105639f40, 0x14000d54140}, {{0xb, 0x0}, {0x140056bca67, 0x7}, 0xf0, {0x183e1da0, ...}, ...}, ...}, ...)
      github.com/cosmos/cosmos-sdk@v0.46.0/x/gov/abci.go:47 +0x334
    github.com/cosmos/cosmos-sdk/x/gov.AppModule.EndBlock(...)
      github.com/cosmos/cosmos-sdk@v0.46.0/x/gov/module.go:199
    github.com/cosmos/cosmos-sdk/types/module.(*Manager).EndBlock(_, {{0x105626830, 0x140000540e8}, {0x105639f40, 0x14000d54140}, {{0xb, 0x0}, {0x140056bca67, 0x7}, 0xf0, ...}, ...}, ...)
      github.com/cosmos/cosmos-sdk@v0.46.0/types/module/module.go:502 +0x40c
    github.com/provenance-io/provenance/app.(*App).EndBlocker(_, {{0x105626830, 0x140000540e8}, {0x105639f40, 0x14000d54140}, {{0xb, 0x0}, {0x140056bca67, 0x7}, 0xf0, ...}, ...}, ...)
      github.com/provenance-io/provenance/app/app.go:844 +0x64
    github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).EndBlock(0x14000ffcfc0, {0x20?})
      github.com/cosmos/cosmos-sdk@v0.46.0/baseapp/abci.go:225 +0x1e4
    github.com/tendermint/tendermint/abci/client.(*localClient).EndBlockSync(0x14000da5620, {0x140055a2308?})
      github.com/tendermint/tendermint@v0.34.21/abci/client/local_client.go:288 +0xf0
    github.com/tendermint/tendermint/proxy.(*appConnConsensus).EndBlockSync(0x14001d3a280?, {0x20?})
      github.com/tendermint/tendermint@v0.34.21/proxy/app_conn.go:89 +0x28
    github.com/tendermint/tendermint/state.execBlockOnProxyApp({0x105627a58?, 0x14001582b40}, {0x1056310f0, 0x140014b91f0}, 0x14000f40b40, {0x1056394c8, 0x140011741c8}, 0xef?)
      github.com/tendermint/tendermint@v0.34.21/state/execution.go:327 +0x414
    github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x0}, {0x1400189e630, 0x8}}, {0x1400189e638, 0x7}, 0x1, 0xef, {{0x14000cd3fe0, ...}, ...}, ...}, ...)
      github.com/tendermint/tendermint@v0.34.21/state/execution.go:140 +0xe4
    github.com/tendermint/tendermint/consensus.(*State).finalizeCommit(0x140001c5c00, 0xf0)
      github.com/tendermint/tendermint@v0.34.21/consensus/state.go:1659 +0x94c
    github.com/tendermint/tendermint/consensus.(*State).tryFinalizeCommit(0x140001c5c00, 0xf0)
      github.com/tendermint/tendermint@v0.34.21/consensus/state.go:1568 +0x288
    github.com/tendermint/tendermint/consensus.(*State).enterCommit.func1()
      github.com/tendermint/tendermint@v0.34.21/consensus/state.go:1503 +0x90
    github.com/tendermint/tendermint/consensus.(*State).enterCommit(0x140001c5c00, 0xf0, 0x0)
      github.com/tendermint/tendermint@v0.34.21/consensus/state.go:1541 +0xb8c
    github.com/tendermint/tendermint/consensus.(*State).addVote(0x140001c5c00, 0x14005271220, {0x0, 0x0})
      github.com/tendermint/tendermint@v0.34.21/consensus/state.go:2155 +0x1678
    github.com/tendermint/tendermint/consensus.(*State).tryAddVote(0x140001c5c00, 0x14005271220, {0x0?, 0x102d12b8c?})
      github.com/tendermint/tendermint@v0.34.21/consensus/state.go:1953 +0x28
    github.com/tendermint/tendermint/consensus.(*State).handleMsg(0x140001c5c00, {{0x105605060?, 0x140015ca890?}, {0x0?, 0x0?}})
      github.com/tendermint/tendermint@v0.34.21/consensus/state.go:856 +0x108
    github.com/tendermint/tendermint/consensus.(*State).receiveRoutine(0x140001c5c00, 0x0)
      github.com/tendermint/tendermint@v0.34.21/consensus/state.go:783 +0x368
    created by github.com/tendermint/tendermint/consensus.(*State).OnStart
      github.com/tendermint/tendermint@v0.34.21/consensus/state.go:379 +0xf4
```

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by SpicyLemon** [comment]
Here's the log messages from right before the error:
```
11:59AM INF received proposal module=consensus proposal={"Type":32,"block_id":{"hash":"DE46B90C37BDE94E3E634522552BBF740AFB25ED4ECF6A043D810186E3EFF1D9","parts":{"hash":"1B690982D3D869005D88A8C8B5E31A691A6BF2E5B31BD24F7FA45ACECB7A7B38","total":1}},"height":25,"pol_round":-1,"round":0,"signature":"MX7vchJX/Ymj0ei9noHRSen1N20ZYeTmtBjddTcz/QqxNPbFaWTnB9Ykf7TEZG0ZmNLNWPqWnwadFj6jnNTwCQ==","timestamp":"2022-09-28T17:59:10.614085Z"}
11:59AM INF received complete proposal block hash=DE46B90C37BDE94E3E634522552BBF740AFB25ED4ECF6A043D810186E3EFF1D9 height=25 module=consensus
11:59AM DBG entering prevote step current={} height=25 module=consensus round=0
11:59AM DBG prevote step: ProposalBlock is valid height=25 module=consensus round=0
11:59AM DBG signed and pushed vote height=25 module=consensus round=0 vote={"block_id":{"hash":"DE46B90C37BDE94E3E634522552BBF740AFB25ED4ECF6A043D810186E3EFF1D9","parts":{"hash":"1B690982D3D869005D88A8C8B5E31A691A6BF2E5B31BD24F7FA45ACECB7A7B38","total":1}},"height":25,"round":0,"signature":"3swm8vgKY5p5jQRp09n7GyLE5bayvd+hBQMDigiOczld5EkEIvFVPA3mcs4BELaH2bM8QicbwKOA+dOnWjfDBA==","timestamp":"2022-09-28T17:59:10.666931Z","type":1,"validator_address":"6DCA7758E0EE7626C4A1AD96187BA7578EDE17FB","validator_index":0}
11:59AM DBG Broadcast channel=32 module=p2p msgBytes={}
11:59AM DBG Attempt to update stats for non-existent peer module=consensus peer=
11:59AM DBG adding vote cs_height=25 module=consensus val_index=0 vote_height=25 vote_type=1
11:59AM DBG Broadcast channel=32 module=p2p msgBytes={}
11:59AM DBG added vote to prevote module=consensus prevotes="VoteSet{H:25 R:0 T:SIGNED_MSG_TYPE_PREVOTE +2/3:DE46B90C37BDE94E3E634522552BBF740AFB25ED4ECF6A043D810186E3EFF1D9:1:1B690982D3D8(1) BA{1:x} map[]}" vote={"block_id":{"hash":"DE46B90C37BDE94E3E634522552BBF740AFB25ED4ECF6A043D810186E3EFF1D9","parts":{"hash":"1B690982D3D869005D88A8C8B5E31A691A6BF2E5B31BD24F7FA45ACECB7A7B38","total":1}},"height":25,"round":0,"signature":"3swm8vgKY5p5jQRp09n7GyLE5bayvd+hBQMDigiOczld5EkEIvFVPA3mcs4BELaH2bM8QicbwKOA+dOnWjfDBA==","timestamp":"2022-09-28T17:59:10.666931Z","type":1,"validator_address":"6DCA7758E0EE7626C4A1AD96187BA7578EDE17FB","validator_index":0}
11:59AM DBG updating valid block because of POL module=consensus pol_round=0 valid_round=-1
11:59AM DBG Broadcast channel=32 module=p2p msgBytes={}
11:59AM DBG entering precommit step current={} height=25 module=consensus round=0
11:59AM DBG precommit step; +2/3 prevoted proposal block; locking hash=DE46B90C37BDE94E3E634522552BBF740AFB25ED4ECF6A043D810186E3EFF1D9 height=25 module=consensus round=0
11:59AM DBG signed and pushed vote height=25 module=consensus round=0 vote={"block_id":{"hash":"DE46B90C37BDE94E3E634522552BBF740AFB25ED4ECF6A043D810186E3EFF1D9","parts":{"hash":"1B690982D3D869005D88A8C8B5E31A691A6BF2E5B31BD24F7FA45ACECB7A7B38","total":1}},"height":25,"round":0,"signature":"hbPLEEYb3mSp/3tHQ9jtAYPmJxRHQMq+eiz9IZOhkslhzBP8Ps5KxjzZLYfOnK9qtO/hNxOw29TswF4Ro6X1Cw==","timestamp":"2022-09-28T17:59:10.703917Z","type":2,"validator_address":"6DCA7758E0EE7626C4A1AD96187BA7578EDE17FB","validator_index":0}
11:59AM DBG Broadcast channel=32 module=p2p msgBytes={}
11:59AM DBG Attempt to update stats for non-existent peer module=consensus peer=
11:59AM DBG adding vote cs_height=25 module=consensus val_index=0 vote_height=25 vote_type=2
11:59AM DBG Broadcast channel=32 module=p2p msgBytes={}
11:59AM DBG added vote to precommit data=Votes:1000000000/1000000000(1.000) height=25 module=consensus round=0 validator=6DCA7758E0EE7626C4A1AD96187BA7578EDE17FB vote_timestamp=2022-09-28T17:59:10Z
11:59AM DBG entering new round with invalid args current={} height=25 module=consensus round=0
11:59AM DBG entering precommit step with invalid args current={} height=25 module=consensus round=0
11:59AM DBG entering commit step commit_round=0 current={} height=25 module=consensus
11:59AM DBG commit is for a locked block; set ProposalBlock=LockedBlock block_hash=DE46B90C37BDE94E3E634522552BBF740AFB25ED4ECF6A043D810186E3EFF1D9 commit_round=0 height=25 module=consensus
11:59AM DBG Broadcast channel=32 module=p2p msgBytes={}
11:59AM INF finalizing commit of block hash={} height=25 module=consensus num_txs=0 root=EA2407D7D00FE4F064898602BB8709F2C28EF76F8E841E8C66BD662D57038F8F
11:59AM DBG committed block block={} height=25 module=consensus
11:59AM ERR CONSENSUS FAILURE!!! {SNIP}
```

**Comment by SpicyLemon** [comment]
Basically, the new way gov props work runs messages through the message handler, but not the antehandler. So the gas meter isn't being turned into a fee gas meter before being run through the message handler (that assumes it's going to be a fee gas meter).

So.... we either need to figure out how to tell the governance module to use a fee gas meter there (might not be possible) or else update the msg_service_router to handle things differently during gov prop processing (when it's not a fee gas meter).

**Comment by SpicyLemon** [comment]
After some discussion, we decided it'd probably be best to just bypass the msg-based fee consumption (in the message service router) if the gas meter isn't a fee gas meter. The assumption here is that the only time that will happen is during the processing of a message that is part of a passed governance proposal.

However, this also means that, if there's a msg-based fee on a message that's in a governance proposal, that fee is ignored.
