### ISSUE TITLE
Panic when using packed config

### ISSUE THREAD

**Issue by dwedul-figure** [provenance-io/provenance#487]
## Summary of Bug

The `provenanced start` command quickly panics when using a packed config file.

## Version

`main-2771406` (a few commits after `v1.7.0`.

## Steps to Reproduce

1. Navigate to the root of the `provenance` repo.
2. `rm -rf build`
3. `make build`
4. `make run-config`
5. `build/provenanced config pack`
6. `make run`

Expected results:
It starts up and runs.

Actual restuls:
```bash
> make run
/Users/danielwedul/git/provenance/build/provenanced -t --home /Users/danielwedul/git/provenance/build/run/provenanced start
2:39PM INF starting ABCI with Tendermint
panic: interface conversion: interface {} is [][]string, not []interface {}

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/server/config.GetConfig(_)
	github.com/cosmos/cosmos-sdk@v0.44.0/server/config/config.go:250 +0xb38
github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x5ff7cf8, 0xc0005a3170}, {0xc00145baf8, 0x7}, {0x5fbe9b0, 0xc001248ec0}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.44.0/server/start.go:248 +0x34b
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc0012efb80, {0xc0014167e0, 0x0, 0x3})
	github.com/cosmos/cosmos-sdk@v0.44.0/server/start.go:129 +0x193
github.com/spf13/cobra.(*Command).execute(0xc0012efb80, {0xc0014167b0, 0x3, 0x3})
	github.com/spf13/cobra@v1.2.1/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc00124b180)
	github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.2.1/command.go:902
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra@v1.2.1/command.go:895
github.com/provenance-io/provenance/cmd/provenanced/cmd.Execute(0xc0000001a0)
	github.com/provenance-io/provenance/cmd/provenanced/cmd/root.go:120 +0x245
main.main()
	github.com/provenance-io/provenance/cmd/provenanced/main.go:12 +0x1e
make: *** [run] Error 2
```

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by dwedul-figure** [comment]
As far as I can tell, the only config value that is `[][]string` is `telemetry.global-labels`. I know there's some special code around that field too.

My first guess on the issue is that, when supplying the packed config to viper, it's now being supplied as a `[][]string` but the app config code that is probably trying to parse it from viper expecting a `[]interface{}` where that `interface{}` is actually also a `[]interface{}`.

I tried giving the `telemetry.global-labels` field a value, but that didn't fix the issue.

Unpacking the config fixes the issue though.
