### ISSUE TITLE
Adding a marker with more than `2^64` coins and minting more panics

### ISSUE THREAD

**Issue by konnov** [provenance-io/provenance#489]
*Surfaced from @informalsystems audit of the release [v1.7.0](https://github.com/provenance-io/provenance/tree/release/v1.7.0)*

## Involved artifacts

- <https://github.com/provenance-io/provenance/blob/release/v1.7.0/x/marker/keeper/marker.go>

## Description

It is possible to add and activate a new marker that has `100000000000000023622` coins, which is more than `2^64`. When we try to mint more coins for that marker, the transaction panics on input validation:

```
Uint64() out of bounds
```

in

https://github.com/provenance-io/provenance/blob/89038513964d54d2efce3ae80592e1c2a0908590/x/marker/keeper/marker.go#L349

## Problem scenarios

Creating and activating a marker that carries more coins than fits into `Uint64`.

## Scenario to reproduce

Using the docker setup from https://github.com/provenance-io/provenance/tree/main/networks/dev

```
provenanced tx marker new 100000000000000023622coldcatcoin --type=COIN --allowGovernanceControl=false --supplyFixed=true --chain-id=chain-dev --from=tp1l2f7duvp36j7mc0vfwevcp5apaed9682hrtng5 --yes -b block
provenanced tx marker grant tp1uncq4lmkffy2crtxpuw755946c5wray2uw42qx coldcatcoin mint --chain-id=chain-dev --from=tp1l2f7duvp36j7mc0vfwevcp5apaed9682hrtng5 --yes -b block
provenanced tx marker grant tp1uncq4lmkffy2crtxpuw755946c5wray2uw42qx coldcatcoin burn --chain-id=chain-dev --from=tp1l2f7duvp36j7mc0vfwevcp5apaed9682hrtng5 --yes -b block
provenanced tx marker finalize coldcatcoin --chain-id=chain-dev --from=tp1l2f7duvp36j7mc0vfwevcp5apaed9682hrtng5 --yes -b block
provenanced tx marker activate coldcatcoin --chain-id=chain-dev --from=tp1l2f7duvp36j7mc0vfwevcp5apaed9682hrtng5 --yes -b block
provenanced tx marker mint 1coldcatcoin --chain-id=chain-dev --from=tp1uncq4lmkffy2crtxpuw755946c5wray2uw42qx --yes -b block
```

The error trace is as follows:

```
Uint64() out of bounds\nstack:\ngoroutine 147 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24
  +0x65\ngithub.com/cosmos/cosmos-sdk/baseapp.newDefaultRecoveryMiddleware.func1({0x1b22c00,
  0x237deb0})\n\tgithub.com/cosmos/cosmos-sdk@v0.44.0/baseapp/recovery.go:71 +0x27\ngithub.com/cosmos/cosmos-sdk/baseapp.newRecoveryMiddleware.func1({0x1b22c00,
  0x237deb0})\n\tgithub.com/cosmos/cosmos-sdk@v0.44.0/baseapp/recovery.go:39 +0x30\ngithub.com/cosmos/cosmos-sdk/baseapp.processRecovery({0x1b22c00,
  0x237deb0}, 0xc00327f680)\n\tgithub.com/cosmos/cosmos-sdk@v0.44.0/baseapp/recovery.go:28
  +0x37\ngithub.com/cosmos/cosmos-sdk/baseapp.processRecovery({0x1b22c00, 0x237deb0},
  0x2422d60)\n\tgithub.com/cosmos/cosmos-sdk@v0.44.0/baseapp/recovery.go:33 +0x5e\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runTx.func1()\n\tgithub.com/cosmos/cosmos-sdk@v0.44.0/baseapp/baseapp.go:598
  +0xfd\npanic({0x1b22c00, 0x237deb0})\n\truntime/panic.go:1038 +0x215\ngithub.com/cosmos/cosmos-sdk/types.Int.Uint64(...)\n\tgithub.com/cosmos/cosmos-sdk@v0.44.0/types/int.go:172\ngithub.com/provenance-io/provenance/x/marker/keeper.Keeper.IncreaseSupply({{{0x241d7d8,
  0xc00119f8d0}, 0xc000b81648, {0x23b7360, 0xc0012ae1b0}, {0x23b73b0, 0xc0012ae290},
  {0xc000035c60, 0x6, 0x1c}, ...}, ...}, ...)\n\tgithub.com/provenance-io/provenance/x/marker/keeper/marker.go:349
  +0x5a5\ngithub.com/provenance-io/provenance/x/marker/keeper.Keeper.MintCoin({{{0x241d7d8,
  0xc00119f8d0}, 0xc000b81648, {0x23b7360, 0xc0012ae1b0}, {0x23b73b0, 0xc0012ae290},
  {0xc000035c60, 0x6, 0x1c}, ...}, ...}, ...)\n\tgithub.com/provenance-io/provenance/x/marker/keeper/marker.go:239
  +0x4e5\ngithub.com/provenance-io/provenance/x/marker/keeper.msgServer.Mint({{{{0x241d7d8,
  0xc00119f8d0}, 0xc000b81648, {0x23b7360, 0xc0012ae1b0}, {0x23b73b0, 0xc0012ae290},
  {0xc000035c60, 0x6, 0x1c}, ...}, ...}}, ...)\n\tgithub.com/provenance-io/provenance/x/marker/keeper/msg_server.go:236
  +0x33e\ngithub.com/provenance-io/provenance/x/marker/types._Msg_Mint_Handler.func1({0x23f3038,
  0xc0031cdc20}, {0x1da9280, 0xc0031c46c0})\n\tgithub.com/provenance-io/provenance/x/marker/types/tx.pb.go:1586
  +0x78\ngithub.com/cosmos/cosmos-sdk/baseapp.(*MsgServiceRouter).RegisterService.func2.1({0x23f3038,
  0xc0031cdbc0}, {0x516646, 0x4145ab}, 0x1e00ba0, 0xc0031aab58)\n\tgithub.com/cosmos/cosmos-sdk@v0.44.0/baseapp/msg_service_router.go:113
  +0xd5\ngithub.com/provenance-io/provenance/x/marker/types._Msg_Mint_Handler({0x1dfc8a0,
  0xc000c89540}, {0x23f3038, 0xc0031cdbc0}, 0x215a698, 0xc0031a5c60)\n\tgithub.com/provenance-io/provenance/x/marker/types/tx.pb.go:1588
  +0x138\ngithub.com/cosmos/cosmos-sdk/baseapp.(*MsgServiceRouter).RegisterService.func2({{0x23f2fc8,
  0xc000136000}, {0x2422d60, 0xc0031a26c0}, {{0xb, 0x0}, {0xc003193e60, 0x9}, 0xf,
  {0xd04d320, ...}, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.44.0/baseapp/msg_service_router.go:117
  +0x34f\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runMsgs(_, {{0x23f2fc8,
  0xc000136000}, {0x2422d60, 0xc0031a26c0}, {{0xb, 0x0}, {0xc003193e60, 0x9}, 0xf,
  ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.44.0/baseapp/baseapp.go:719
  +0x46a\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runTx(0xc00128cb60, 0x3,
  {0xc000c1d9e0, 0x118, 0x118})\n\tgithub.com/cosmos/cosmos-sdk@v0.44.0/baseapp/baseapp.go:679
  +0xa2c\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).DeliverTx(0xc00128cb60,
  {{0xc000c1d9e0, 0x18, 0x0}})\n\tgithub.com/cosmos/cosmos-sdk@v0.44.0/baseapp/abci.go:275
  +0x1df\ngithub.com/tendermint/tendermint/abci/client.(*localClient).DeliverTxAsync(0xc0010691a0,
  {{0xc000c1d9e0, 0x0, 0xc0010691a0}})\n\tgithub.com/tendermint/tendermint@v0.34.12/abci/client/local_client.go:87
  +0x105\ngithub.com/tendermint/tendermint/proxy.(*appConnConsensus).DeliverTxAsync(0xc003266cc0,
  {{0xc000c1d9e0, 0x20, 0xb}})\n\tgithub.com/tendermint/tendermint@v0.34.12/proxy/app_conn.go:85
  +0x26\ngithub.com/tendermint/tendermint/state.execBlockOnProxyApp({0x23f3e00, 0xc0012682a0},
  {0x240b2d0, 0xc0011ab3f0}, 0xc000bf14a0, {0x241b418, 0xc0011aa790}, 0xe)\n\tgithub.com/tendermint/tendermint@v0.34.12/state/execution.go:320
  +0x822\ngithub.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(_, {{{0xb,
  0x0}, {0xc0010b9a10, 0x8}}, {0xc0010b9a20, 0x9}, 0x1, 0xe, {{0xc002f369c0, ...},
  ...}, ...}, ...)\n\tgithub.com/tendermint/tendermint@v0.34.12/state/execution.go:140
  +0x171\ngithub.com/tendermint/tendermint/consensus.(*State).finalizeCommit(0xc000cc7500,
  0xf)\n\tgithub.com/tendermint/tendermint@v0.34.12/consensus/state.go:1635 +0x9fd\ngithub.com/tendermint/tendermint/consensus.(*State).tryFinalizeCommit(0xc000cc7500,
  0xf)\n\tgithub.com/tendermint/tendermint@v0.34.12/consensus/state.go:1546 +0x305\ngithub.com/tendermint/tendermint/consensus.(*State).enterCommit.func1()\n\tgithub.com/tendermint/tendermint@v0.34.12/consensus/state.go:1481
  +0x87\ngithub.com/tendermint/tendermint/consensus.(*State).enterCommit(0xc000cc7500,
  0xf, 0x0)\n\tgithub.com/tendermint/tendermint@v0.34.12/consensus/state.go:1519 +0xc06\ngithub.com/tendermint/tendermint/consensus.(*State).addVote(0xc000cc7500,
  0xc002672500, {0x0, 0x0})\n\tgithub.com/tendermint/tendermint@v0.34.12/consensus/state.go:2132
  +0xb6e\ngithub.com/tendermint/tendermint/consensus.(*State).tryAddVote(0xc000cc7500,
  0xc002672500, {0x0, 0xc0029dfbb8})\n\tgithub.com/tendermint/tendermint@v0.34.12/consensus/state.go:1930
  +0x2c\ngithub.com/tendermint/tendermint/consensus.(*State).handleMsg(0xc000cc7500,
  {{0x23a88e0, 0xc002e50458}, {0x0, 0x0}})\n\tgithub.com/tendermint/tendermint@v0.34.12/consensus/state.go:838
  +0x3dc\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine(0xc000cc7500,
  0x0)\n\tgithub.com/tendermint/tendermint@v0.34.12/consensus/state.go:782 +0x512\ncreated
  by github.com/tendermint/tendermint/consensus.(*State).OnStart\n\tgithub.com/tendermint/tendermint@v0.34.12/consensus/state.go:378
  +0x12f\n: panic"
```

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by konnov** [comment]
The same happens, if the administrator is trying to mint `nhash`.

**Comment by konnov** [comment]
There is a similar scenario, where we start with just 1 coin and try to mint too many:

```
provenanced tx marker new 1coldcatcoin --type=COIN --allowGovernanceControl=false --supplyFixed=true --chain-id=chain-dev --from=tp1l2f7duvp36j7mc0vfwevcp5apaed9682hrtng5 --yes -b block
provenanced tx marker grant tp1uncq4lmkffy2crtxpuw755946c5wray2uw42qx coldcatcoin burn --chain-id=chain-dev --from=tp1l2f7duvp36j7mc0vfwevcp5apaed9682hrtng5 --yes -b block
provenanced tx marker grant tp1uncq4lmkffy2crtxpuw755946c5wray2uw42qx coldcatcoin mint --chain-id=chain-dev --from=tp1l2f7duvp36j7mc0vfwevcp5apaed9682hrtng5 --yes -b block
provenanced tx marker finalize coldcatcoin --chain-id=chain-dev --from=tp1l2f7duvp36j7mc0vfwevcp5apaed9682hrtng5 --yes -b block
provenanced tx marker activate coldcatcoin --chain-id=chain-dev --from=tp1l2f7duvp36j7mc0vfwevcp5apaed9682hrtng5 --yes -b block
provenanced tx marker mint 100433627766186892221372630771322662657637687111424552206335coldcatcoin --chain-id=chain-dev --from=tp1uncq4lmkffy2crtxpuw755946c5wray2uw42qx --yes -b block
```

**Comment by iramiller** [comment]
Curious if you have the supply limits in place. There is a default of about 100M as I recall we will look at this.

**Comment by konnov** [comment]
Yes, it is the standard genesis from the dev testing: https://github.com/provenance-io/provenance/tree/main/networks/dev
